#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in; // group size
layout(std430, binding = 0) buffer Vertices { float vertices[]; }; // our ssbo binding at slot 0

// uniform variables
uniform uint closestId;
uniform float radius;
uniform uint vertsCount;
uniform bool isGrow;
uniform float growAmount;

/// helper function since we're storing the data as an array of float
vec3 getVertexVec3(uint id) {
    uint base = id * 3;
    return vec3(vertices[base], vertices[base+1], vertices[base+2]);
}

void setVertexVec3(uint id, vec3 v){
    uint base = id * 3;
    vertices[base] = v.x;
    vertices[base+1] = v.y;
    vertices[base+2] = v.z;
}

void main(){
    // id of each thread
    // this is per vertex
    uint id = gl_GlobalInvocationID.x;
    if (id >= vertsCount) return; // prevent out of bound access

    vec3 center = getVertexVec3(closestId); // defining the closest vertex to our ray as the center
    vec3 pos = getVertexVec3(id);
    float dist = distance(center, pos);

    // if the distance between current vertex and center is greater than the radius,
    // then it should not be modified
    if (dist > radius) return;

    // toggle for whether to increase or decrease height
    if (isGrow){
        pos.y += growAmount;
    }
    else{
        pos.y -= growAmount;
    }

    setVertexVec3(id, pos); // write to ssbo
}