#version 430 core

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;
layout(std430, binding = 0) buffer Vertices { float vertices[]; };

uniform uint closestId;
uniform float radius;
uniform uint vertsCount;
uniform bool isGrow;
uniform float growAmount;

vec3 getVertexVec3(uint id) {
    uint base = id * 3;
    return vec3(vertices[base], vertices[base+1], vertices[base+2]);
}

void setVertexVec3(uint id, vec3 v){
    uint base = id * 3;
    vertices[base] = v.x;
    vertices[base+1] = v.y;
    vertices[base+2] = v.z;
}

void main(){
    uint id = gl_GlobalInvocationID.x;
    if (id >= vertsCount) return;

    vec3 center = getVertexVec3(closestId);
    vec3 pos = getVertexVec3(id);
    float dist = distance(center, pos);
    if (dist > radius) return;

    if (isGrow){
        pos.y += growAmount;
    }
    else{
        pos.y -= growAmount;
    }

    setVertexVec3(id, pos);
}